### PR TITLE
stuff added to data/moose_testdb.json to enable testing of wacky cases

### PR DESCRIPTION
**Pull request by WilkAndy**
### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

### CODE REVIEW

**Comment by WilkAndy** [comment]
Oh, i just saw that this contains two commits.  Strange - one removes some database.md stuff, and the next commit adds it back again.  I think my faulty "git rebase" must have done that.

**Comment by cpgr** [comment]
I'm going to stop work on this PR as it is getting hard to keep rebasing properly!

**Comment by WilkAndy** [comment]
OK.  i'll only add to it if i desperately need functionality, but i don't think i will, unless the MOOSE guys take a week to merge it.

**Comment by cpgr** [comment]
Enjoy your weekend Andy!

**Comment by WilkAndy** [comment]
Thanks Chris, i hope you have a good weekend too.  It's study time here (children) so i might be doing some MOOSE coding.

**Pull request merged**
