### PR TITLE
quickly cast your eyes over the new methods (especially const, returning references) before merging

### PR DESCRIPTION
**Pull request by WilkAndy**
more methods added to GeochemicalDatabaseReader that i am using in other code.  More tests added to units tests for these methods and others i added yesterday.  moose_testdb.json extended to allow further testing, etc

### Complete each of the following items before creating a PR

- Include any relevant design information for your change
- Follow [Coding Standards](http://mooseframework.org/wiki/CodeStandards/)
- Submit one or more [Test Cases](http://mooseframework.org/wiki/MooseTraining/testing/) or modify existing test cases
- Reference or close a specific issue (refs # or closes #)

### CODE REVIEW

**Comment by cpgr** [comment]
I think that we should change how the sorbing_minerals are added to the JSON, so that site_density is a subfield of sorbing_site, like how the stoichiometries are attached to the basis species in other cases. Then we wouldn't have to worry about indexing into different vectors.

So instead of
```
  "sorbing minerals": {
    "Fe(OH)3(ppd)": {
      "site density": [
        ".0050",
        ".2000"
      ],
      "sorbing site": [
        ">(s)FeOH",
        ">(w)FeOH"
      ],
      "surface area": "600.0000"
    },
```
have
```
  "sorbing minerals": {
    "Fe(OH)3(ppd)": {
      "sorbing site": [
        ">(s)FeOH": "0.0050",
        ">(w)FeOH": ".2000"
      ],
      "surface area": "600.0000"
    },
```
and associated changes in the C++ code

**Comment by WilkAndy** [comment]
OK, i'm doing similar stuff right now, so great minds think alike.  Don't merge this till i've issued another PR

**Comment by WilkAndy** [comment]
done

**Comment by cpgr** [comment]
Thanks Andy.

I might just add a bit of doc about the format and then we could let it get merged, and add bits as needed as we move on to other things.

**Comment by WilkAndy** [comment]
Yea, i'm doing a lot on the "MinimalGeochemicalSystem", which is eliminating all extraneous information that is contained in the Reader.  It's a lot of work, and i'm not adding it to this PR, otherwise it'll double in size.

**Pull request merged**
